In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


In [23]:
df = pd.read_csv('Admission_Predict.csv');

In [24]:
df.shape

(400, 9)

In [25]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [26]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [27]:
df.head()


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [81]:
df.loc[df['Chance of Admit '] < 0.75, 'Chance of Admit '] = 0
df.loc[df['Chance of Admit '] >= 0.75, 'Chance of Admit '] = 1
X = df.drop(['Chance of Admit ','Serial No.'],axis=1)
X=df.iloc[:,1:8].values
X

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  , ...,   4.5 ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  , ...,   4.  ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  , ...,   4.  ,   9.66,   1.  ]])

In [69]:
y=df['Chance of Admit ']
y

0      1.0
1      1.0
2      0.0
3      1.0
4      0.0
      ... 
395    1.0
396    1.0
397    1.0
398    0.0
399    1.0
Name: Chance of Admit , Length: 400, dtype: float64

In [70]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.25,random_state=25)
X_train

array([[314.  , 103.  ,   2.  , ...,   3.  ,   8.21,   0.  ],
       [324.  , 105.  ,   3.  , ...,   4.  ,   8.75,   0.  ],
       [321.  , 111.  ,   3.  , ...,   3.  ,   8.9 ,   1.  ],
       ...,
       [340.  , 120.  ,   4.  , ...,   4.  ,   9.92,   1.  ],
       [324.  , 111.  ,   3.  , ...,   2.  ,   8.8 ,   1.  ],
       [309.  , 105.  ,   5.  , ...,   3.5 ,   8.56,   0.  ]])

In [71]:
Y_train

4      0.0
153    1.0
283    1.0
276    1.0
239    0.0
      ... 
374    0.0
317    0.0
143    1.0
318    1.0
132    0.0
Name: Chance of Admit , Length: 300, dtype: float64

In [72]:
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn import metrics

classify = dtc()
classify=classify.fit(X_train,Y_train)

In [73]:
y_pred = classify.predict(X_test)
y_pred

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1.])

In [74]:
print("confusion matrix:\n")
print(metrics.confusion_matrix(Y_test, y_pred))

confusion matrix:

[[45 12]
 [ 6 37]]


In [75]:
metrics.accuracy_score(Y_test, y_pred)

0.82

In [76]:
metrics.precision_score(Y_test, y_pred)

0.7551020408163265

In [77]:
metrics.recall_score(Y_test, y_pred)

0.8604651162790697

In [78]:
metrics.f1_score(Y_test, y_pred)

0.8043478260869564

In [79]:
pred = classify.predict([[320,105,2,2.0,3.0,8.35,0]])
pred

array([0.])